sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t sujeetkp/react-test ./client

script:
    - docker run -e CI=true sujeetkp/react-test npm run test

after_success:
    - docker build -t sujeetkp/multi-client ./client
    - docker build -t sujeetkp/multi-server ./server
    - docker build -t sujeetkp/multi-nginx ./nginx
    - docker build -t sujeetkp/multi-worker ./worker

    # Login to Docker hub using Doker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Take the images and push to Docker Hub
    - docker push sujeetkp/multi-client
    - docker push sujeetkp/multi-server
    - docker push sujeetkp/multi-nginx
    - docker push sujeetkp/multi-worker


    
