version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password    # Set a Default Password for Postgres
    redis:
        image: 'redis:latest'
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis               # Redis Service Name
            - REDIS_PORT=6379                # Default Redis Port
            - PGUSER=postgres                # Default Postgres user
            - PGPASSWORD=postgres_password   # Default Postgres Password assigned to POSTGRES_PASSWORD
            - PGHOST=postgres                # Postgres Service Name
            - PGPORT=5432                    # Default Postgres Port
            - PGDATABASE=postgres            # Default Postgres Databse    
        depends_on: 
            - postgres
            - redis
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        depends_on: 
            - api
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        depends_on: 
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "3050:80"
        depends_on: 
            - client
